# Generated by Django 5.1.3 on 2024-11-30 19:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True)),
                ('generic_name', models.CharField()),
                ('brand_name', models.CharField(null=True)),
                ('form', models.CharField()),
                ('strength', models.CharField()),
                ('pack_size', models.IntegerField()),
                ('cost_price_pack', models.DecimalField(decimal_places=2, max_digits=7)),
                ('selling_price_pack', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
