# Generated by Django 5.1.3 on 2025-01-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0008_rename_uuid_facilityproduct_id'),
        ('sales', '0002_rename_products_cart_facility_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderProducts',
            new_name='OrderProduct',
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('out of pocket', 'Out of pocket'), ('online payment', 'Online Payment'), ('no cost', 'Provide at no cost')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('insurance', 'Insurance'), ('out of pocket', 'Out of pocket'), ('online payment', 'Online Payment'), ('no cost', 'Provide at no cost')]),
        ),
    ]
