# Generated by Django 5.1.3 on 2025-01-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='has_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='slug',
            field=models.CharField(null=True, unique=True),
        ),
    ]
