# Generated by Django 5.1.3 on 2025-01-04 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_has_delivery_alter_facility_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilityproduct',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
