# Generated by Django 5.1.3 on 2025-01-15 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facilityproduct_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityproduct',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, serialize=False, unique=True),
        ),
    ]
