# Generated by Django 5.1.3 on 2025-01-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_facilityproduct_created_at_facilityproduct_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facilityproduct',
            old_name='uuid',
            new_name='id',
        ),
    ]
