# Generated by Django 5.1.3 on 2024-12-14 18:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0007_client_slug'),
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='modified_at')),
                ('is_active', models.BooleanField(default=True)),
                ('payment_method', models.CharField(choices=[('insurance', 'Insurance'), ('corporate', 'Corporate'), ('out_of_pocket', 'Out of Pocket')])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facility')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('facility_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facilities.facilityproduct')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='facility_products',
            field=models.ManyToManyField(through='cart.SaleProduct', to='facilities.facilityproduct'),
        ),
    ]
