# Generated by Django 5.1.3 on 2024-12-06 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_facilitywarehousetransfers_transfer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productswarehouseinbound',
            name='inbound',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_products', to='warehouse.warehouseinbound'),
        ),
    ]
