# Generated by Django 5.1.3 on 2024-12-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_productswarehouseinbound_inbound'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductsWarehouseInbound',
            new_name='WarehouseProductsInbound',
        ),
        migrations.RemoveField(
            model_name='warehouseinbound',
            name='warehouse_products',
        ),
        migrations.AddField(
            model_name='warehouseinbound',
            name='products',
            field=models.ManyToManyField(through='warehouse.WarehouseProductsInbound', to='warehouse.warehouseproduct'),
        ),
    ]
