# Generated by Django 5.1.3 on 2024-12-31 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_rename_productswarehouseinbound_warehouseproductsinbound_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warehouseinbound',
            old_name='products',
            new_name='warehouse_products',
        ),
    ]
