# Generated by Django 5.1.3 on 2024-12-08 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='parent_facility',
        ),
    ]
