# Generated by Django 5.1.3 on 2024-12-17 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_client_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='slug',
        ),
    ]
