# Generated by Django 5.1.3 on 2024-12-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_remove_client_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
