# Generated by Django 5.1.3 on 2024-12-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_client_is_client'),
        ('token_blacklist', '0012_alter_outstandingtoken_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOutstandingToken',
            fields=[
                ('outstandingtoken_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='token_blacklist.outstandingtoken')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.client')),
            ],
            bases=('token_blacklist.outstandingtoken',),
        ),
    ]
